# Conclusion

In this project, we produce an exploratory data analysis on NBA players’ statistics and salaries. We utilized dot plot, heatmaps, parallel coordinate plot, and etc. to analyze the normality, modality, and distributions of the dataset. We discover that the NBA players’ salaries roughly follow a normal distribution, and there is a positive correlation between their performance and salary — the number of games, average points/min/rebounds/assists per game are positively correlated to the player salaries. We also discretize the age and salary data to categorical variables to explore the play composition in each team and how age affects the players’ salaries. We notice that major players in different groups have similar salary variance, and the players in middle age (25-33) tend to have the highest median, and there are more superstar players in peak performance that have extremely high salaries, where they are salary outliers in this category.

Our figures not only show some superficial relationships and features, but also reveal some hidden information that the original data did not express. This indicates that our project not only stops at simple data analysis, but also provides a direction for continuing to explore data. For example, in our PCA analysis, we were surprised to find that the adjacent feature can represent the position information of the player (we eliminate this when cleaning data considering the ambiguity of position). The data points in the upper right corner are often inside players, where their arrows point to the same direction of rebounds and blocks in the original feature. The data points in the lower left corner are often outside players, and their arrows points to the same direction as three-pointers and free throws. In the salary ridgeline plot with respect to the player teams, we can roughly infer the team's player composition structure (how many cores, whether it is a playoff team or not).

By comparing with the reality, we conclude several limitations of our analysis. First and foremost, we do not take into account the impact of team market value and playoff performance in recent years on salaries. Some wealthy teams are more willing to pay high salaries for high-level players, while owners of small ball markets do not have the ability to afford excessive luxury taxes. Secondly, we did not take into account the impact of player injuries, trades, and off-field public opinion on their performance. For example, the sudden drop of performance caused by injury, stars with special significance to a certain team, and players with negative news influence outside the court are potential noise in the data that we are not eliminating. Lastly, for certain years, the players’ performance are not associated with their salaries. Because of the availability of the datasets, we use the mean of the 2022-2028 salaries, which could be more vulnerable to the noise mentioned above. In addition, it is too utilitarian to use rigid data to measure players, and the value of some players cannot only be expressed through these basic data.

During the playoffs, the performance of key players can often determine the future of a team. Therefore, in addition to the regular season, key players’ achievement is a crucial factor. For example, Jordan Pool earns a profitable salary because of his great performance in GSW’s champion playoffs. In the future, we will consider integrating both the regular season and playoff data for more accurate analysis. To overcome the limited representation of the basic data, we will also contemplate higher-level statistics such as player plus/minus (whether a player's presence wins points for the team), shooting efficiency (the number of points a player can make with his shots), and player defensive efficiency (how much his defense can give the opponent shooting precision drop). 

Throughout this project, we acquire a better understanding of the basic pipeline of explorative data analysis, regarding how informative the simple datasets can be. We master the skills to visualize the data and deliver our findings to the audience professionally using plotting languages. We also familiarized ourselves with data preprocessing techniques, and get more understanding of how to make our data tidy to serve for the more complicated analysis such as fitting and prediction in our future study.

