# Proposal

## Research topic

In sports leagues, there tends to be huge gaps in the salaries among different players. Some superstars may earn hundreds of times as much as other regular players. On the other hand, some players may have been paid salaries that do not match their abilities. Our group decided to explore and evaluate a player’s deserving salary based on his contribution to the field. In our project, we will focus on the National Basketball Association (NBA) league and obtain the latest player statistics for the last few seasons from the Basketball Reference. Our goal is to work as data scientists to develop reasonable salary plans for NBA team owners based on historical statistics and data summary. 

## Data availability

Our data source is from the [BasketBall Reference](https://www.basketball-reference.com/), a website serving up NBA and WNBA statistics, scores and history. The BasketBall Reference keeps pace with the times, updates the daily data and saves all the historical data since the creation of the NBA. The BasketBall Reference is using the official NBA data, and the data is provided by SportRadar, the official statistics provider of the NBA. Since the data is from the website in an unstructured format, we will scrape the website (specifically from the season summary and the contracts section) and store the data in csv files using rvest.

Since we wanted to explore the data from latest five years, we need to aggregate data from multiple pages. To import data, we utilized a loop function to scrape the data from multiple pages and collected the HTML data. Then we extracted column headers and rows, and added “year” as a column. After that, we created dataframe and exported to csv. Lastly, we combined all the data tables using the join function.

### Season summary

From this website, we will obtain our roster and player statics dataset from the [season summary](https://www.basketball-reference.com/leagues/) page, which records the conference standings, division standings, playoff series, per game statics, and advanced stats. We will join these tables to measure the overall performance of the players. 

| Award Winners | Top Performers |                       |                  |                    |                  |                 |                    |                  |
| :------------ | :------------: | :-------------------: | :--------------: | :----------------: | :--------------: | :-------------: | :----------------: | :--------------: |
| Season        |       Lg       |       Champion        |       MVP        | Rookie of the Year |      Points      |    Rebounds     |      Assists       |    Win Shares    |
| 2022-23       |      NBA       |                       |                  |                    | K. Durant (192)  | R. Gobert (91)  | T. Haliburton (70) |  N. Jokić (1.2)  |
| 2021-22       |      NBA       | Golden State Warriors |     N. Jokić     |     S. Barnes      | T. Young (2155)  | N. Jokić (1019) |   T. Young (737)   | N. Jokić (15.2)  |
| 2020-21       |      NBA       |    Milwaukee Bucks    |     N. Jokić     |      L. Ball       | S. Curry (2015)  | R. Gobert (960) | R. Westbrook (763) | N. Jokić (15.6)  |
| 2019-20       |      NBA       |  Los Angeles Lakers   | G. Antetokounmpo |     J. Morant      | J. Harden (2335) | R. Gobert (916) |   L. James (684)   | J. Harden (13.1) |

Note that this is just a rough measurement of player performance, because some players' value cannot be simply reflected by the data. Another assumption underlying is that the games are equally weighted, and we are ignoring the bias of some more important games.


### Contract

Players' income data is stored in [contracts](https://www.basketball-reference.com/contracts/players.html), which includes the salaries of NBA players. For example, the largest contracts in the leaderboard are:

|      | Salary            |      |             |             |             |             |         |         |              |
| ---: | :---------------- | :--- | :---------: | :---------: | :---------: | :---------: | :-----: | :-----: | -----------: |
|   Rk | Player            | Tm   |   2022-23   |   2023-24   |   2024-25   |   2025-26   | 2026-27 | 2027-28 |   Guaranteed |
|    1 | Stephen Curry     | GSW  | $48,070,014 | $51,915,615 | $55,761,216 | $59,606,817 |         |         | $215,353,662 |
|    2 | Russell Westbrook | LAL  | $47,063,478 |             |             |             |         |         |  $47,063,478 |
|    3 | LeBron James      | LAL  | $44,474,988 | $53,369,986 | $57,639,585 |             |         |         |  $97,844,974 |
|    4 | Kevin Durant      | BRK  | $44,119,845 | $47,649,433 | $51,179,021 | $54,708,609 |         |         | $197,656,908 |


### Miscellaneous 

The Basketball Reference also provides some other data, such as playoff teams, team winning rate, salary caps, player agent company, and etc. In the project, we assume the player salaries are not affected by these external factors, and they are only determined by players' performance on the court.
